import PublicLayout from '../components/PublicLayout';
export default function PrivacyPage() {
  return <PublicLayout title="Privacy policy" description="This policy describes the data processing implemented by CV Creator Pro. Review the deployment operator's contact details before using a hosted instance."><article className="card p-6 sm:p-10 max-w-4xl space-y-7 leading-relaxed text-sm">
    <section><h2 className="text-lg font-semibold mb-2">Data you provide</h2><p>We store your account name and email, a password hash, session records, resume content, cover letters, preferences, and AI usage counts. Passwords are hashed; session credentials are held in an HttpOnly cookie. Resume files uploaded for import are processed to extract their text.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Why we process it</h2><p>We use this information to sign you in, save your documents, render templates, generate exports, apply your preferences, protect accounts, and enforce usage limits. We do not sell your resume content or publish it automatically.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">AI processing and third parties</h2><p>When you choose an AI action, the relevant resume text, job description, and other information you submit are sent to OpenRouter and the configured model provider to produce the result. Those providers process requests under their own terms and privacy policies. Only submit information you are comfortable sharing with them. Normal editing and exports do not require an AI request.</p><p className="mt-2">External fonts may be loaded from Google Fonts. Their service can receive standard connection information such as your IP address. The operator may use hosting and database services to run this application.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Retention and deletion</h2><p>Saved documents remain until you delete them or your account. Delete individual resumes or cover letters from the dashboard, or delete your account in Settings by confirming your password. Account deletion removes the associated saved documents and sessions from the active database. Backups and third-party AI processing may follow separate retention schedules controlled by the deployment operator or provider.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Your choices</h2><p>You can inspect and edit your saved documents, download copies in available export formats, change your password, and delete your account. The theme preference is also stored in your browser. The career assistant saves requested AI analyses in your account; use its Clear history action to remove saved results. Usage audit counts are retained until account deletion.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Deployment and contact</h2><p>This codebase does not assign a legal operator, postal address, or privacy contact. For a public deployment, the operator must provide their identity, contact channel, applicable retention periods, and any additional disclosures required for the services they connect.</p></section>
  </article></PublicLayout>;
}
