import PublicLayout from '../components/PublicLayout';
import { SITE, supportMailto } from '../lib/site';

export default function PrivacyPage() {
  return <PublicLayout title="Privacy policy" description={`Last updated ${SITE.lastUpdated}`}><article className="card p-6 sm:p-10 max-w-4xl space-y-7 leading-relaxed text-sm">
    <section><h2 className="text-lg font-semibold mb-2">Who is responsible</h2><p>{SITE.name} is operated by {SITE.operator}, {SITE.location}. Privacy requests can be sent to <a className="text-blue-600 hover:underline" href={supportMailto}>{SITE.supportEmail}</a>.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Information we process</h2><p>We process account information such as your name, email address, password hash, session records, preferences, plan, and usage. We also process documents you save, imported text, AI requests and saved results, and information you send to support. Hosting services process technical connection information, such as IP addresses, to deliver and protect the service. When payments are enabled, we receive subscription identifiers and status from the payment provider. We do not receive or store full payment card details.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Purposes and legal grounds</h2><p>We use this information to create and secure your account, save and export documents, provide requested features, enforce plan limits, support billing, answer support requests, prevent abuse, and meet legal obligations. Processing is based on providing the service you request, our legitimate interests in security and improvement, consent where required, and compliance with law.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Automated writing features</h2><p>When you use AI writing, resume import, or analysis, relevant document text, job descriptions, and instructions are sent through OpenRouter to the configured model provider. This may include personal information contained in your resume. Manual editing, previews, and standard exports do not require this transfer. Only submit information you are entitled to share and review AI results before use. Provider retention and data use depend on their policies and the selected model; see <a className="text-blue-600 underline" href="https://openrouter.ai/privacy" target="_blank" rel="noreferrer">OpenRouter's Privacy Policy</a>. We do not use these features to make employment decisions about you.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Service providers and international processing</h2><p>Railway hosts the application and database. OpenRouter and its model providers process AI requests. When configured, Resend delivers account recovery emails. Google Fonts provides the interface typeface and receives a browser request when it loads. When paid subscriptions are enabled, Lemon Squeezy handles checkout, invoices, transaction taxes, and refunds as merchant of record; its <a className="text-blue-600 underline" href="https://www.lemonsqueezy.com/privacy" target="_blank" rel="noreferrer">Privacy Policy</a> applies. Providers may process information outside Morocco. Their applicable terms, privacy practices, and transfer safeguards govern their own processing.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Retention and security</h2><p>Saved documents and AI history remain in your account until deleted. Account deletion removes its records and saved documents from the active application database. Cancel a renewing subscription first so it cannot continue charging after closure. Support correspondence, security records, provider backups, and legally required billing records may follow separate retention periods. Browser draft copies can remain on your device until cleared. Passwords are hashed, production sessions use secure HttpOnly cookies, and document access requires account authentication.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Your choices and rights</h2><p>You can review and edit documents, download a copy of your profile and saved documents, clear saved analyses, change your password, and delete your account in Settings. Depending on your location, you may also request access, correction, deletion, restriction, portability, or objection. Depending on applicable law, you may complain to the competent privacy authority. We may need to verify your identity before completing a request.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Cookies and browser storage</h2><p>The necessary cv_session cookie keeps you signed in. Browser local storage remembers your theme and keeps recovery copies of unsaved resume changes. Remove these through your browser site-data settings; clearing the authentication cookie signs you out and clearing drafts may remove unsaved changes. The application does not include advertising trackers or third-party analytics. External checkout services apply their own cookie policies. The service is not directed to children under 16, and users must meet the minimum age required to enter a contract in their country.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Contact</h2><p>Email privacy questions or requests to <a className="text-blue-600 hover:underline" href={supportMailto}>{SITE.supportEmail}</a>.</p></section>
  </article></PublicLayout>;
}
