import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowDown, ArrowUp, Check, ChevronLeft, Copy, Download, Eye, GripVertical, Loader2, Plus, Redo2, Save, Sparkles, Trash2, Undo2, X } from 'lucide-react';
import AppLayout from '../components/AppLayout';
import ResumeCreationWizard from '../components/ResumeCreationWizard';
import { TEMPLATE_LIST, getTemplate } from '../components/templates/ResumeTemplates';
import { createResumePDF } from '../components/templates/ResumePDF';
import { downloadBlob, downloadText, exportTextDOCX } from '../lib/documentExports';
import { useResumeEditor } from '../lib/useResumeEditor';
import { api } from '../lib/api';
import { useToast } from '../contexts/ToastContext';
import { useAuth } from '../contexts/AuthContext';
import { ENTRY_FIELDS, SECTION_IDS, SECTION_LABELS, parseEnabledSections, parseSectionOrder, resumeBlocks, resumeToText } from '../types/resume';
import type { Resume, RelationKey, SectionId } from '../types/resume';

type EditableEntry = Record<string,string|number|boolean|undefined>;
const relationFor:Record<Exclude<SectionId,'summary'>,RelationKey>={experience:'experiences',education:'educations',skills:'skills',projects:'projects',certifications:'certifications',languages:'languages',awards:'awards',publications:'publications',volunteer:'volunteer',interests:'interests',references:'references'};
const fieldLabels:Record<string,string>={jobTitle:'Job title',company:'Company',location:'Location',employmentType:'Employment type',startDate:'Start date',endDate:'End date',description:'Description / responsibilities',achievements:'Verified achievements',technologies:'Technologies',institution:'Institution',degree:'Degree',fieldOfStudy:'Field of study',grade:'Grade / GPA',name:'Name',category:'Category',level:'Level',projectUrl:'Project URL',githubUrl:'GitHub URL',issuer:'Issuer',issueDate:'Issue date',expiryDate:'Expiry date',credentialId:'Credential ID',credentialUrl:'Credential URL',title:'Title',date:'Date',publisher:'Publisher',url:'URL',organization:'Organization',role:'Role',position:'Position',email:'Email',phone:'Phone'};
const longFields=new Set(['description','achievements']);
const personalFields:[keyof Resume,string][]=[['fullName','Full name'],['professionalTitle','Professional title'],['email','Email'],['phone','Phone'],['city','City'],['country','Country'],['linkedinUrl','LinkedIn URL'],['githubUrl','GitHub URL'],['portfolioUrl','Portfolio URL'],['targetRole','Target role'],['targetCompany','Target company']];
interface AISuggestion {kind:'summary'|'experience';values:string[];key?:string;original:string;explanation?:string}
export default function ResumeEditor({isNew}:{isNew?:boolean}){return isNew?<ResumeCreationWizard/>:<ExistingResumeEditor/>;}

function ExistingResumeEditor(){
  const {id}=useParams();const navigate=useNavigate();const toast=useToast();const {user}=useAuth();
  const {resume,loading,error,saveStatus,save,update,undo,redo,historyCount,recovery,restore,discardRecovery}=useResumeEditor(id);
  const [panel,setPanel]=useState<'content'|'design'|'sections'|'job'>('content'),[mobilePreview,setMobilePreview]=useState(false);
  const [previewURL,setPreviewURL]=useState(''),[previewError,setPreviewError]=useState(''),[previewBusy,setPreviewBusy]=useState(false);
  const previewURLRef=useRef(''),currentResume=useRef<Resume|null>(resume);currentResume.current=resume;
  const [exporting,setExporting]=useState(''),[aiBusy,setAiBusy]=useState(''),[suggestion,setSuggestion]=useState<AISuggestion|null>(null);
  const suggestionDialog=useRef<HTMLDivElement>(null);
  const [aiConfigured,setAiConfigured]=useState<boolean|null>(null),[job,setJob]=useState(''),[aiResult,setAiResult]=useState<Record<string,unknown>|null>(null);
  const [tone,setTone]=useState('professional');
  const documentIdentity=useRef(id);documentIdentity.current=id;
  const signature=resume?JSON.stringify({...resume,updatedAt:undefined,completionScore:undefined}):'';
  useEffect(()=>{let active=true;void api.get<{ai:{configured:boolean}}>('/config').then(r=>{if(active)setAiConfigured(r.ai.configured);}).catch(()=>{if(active)setAiConfigured(false);});return()=>{active=false;};},[]);
  useEffect(()=>{
    if(!resume)return;let active=true;setPreviewBusy(true);const snapshot=resume;
    const timer=setTimeout(()=>{void createResumePDF(snapshot).then(blob=>{
      if(!active)return;const url=URL.createObjectURL(blob);if(previewURLRef.current)URL.revokeObjectURL(previewURLRef.current);previewURLRef.current=url;setPreviewURL(url);setPreviewError('');
    }).catch(err=>{if(active)setPreviewError(err instanceof Error?err.message:'Preview could not update');}).finally(()=>{if(active)setPreviewBusy(false);});},700);
    return()=>{active=false;clearTimeout(timer);};
  // signature excludes server metadata, so successful saves do not regenerate the PDF.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[signature]);
  useEffect(()=>()=>{if(previewURLRef.current)URL.revokeObjectURL(previewURLRef.current);},[]);
  useEffect(()=>{setSuggestion(null);setAiResult(null);},[id]);
  useEffect(()=>{
    if(!suggestion)return;const previous=document.activeElement as HTMLElement|null;
    const focusable=()=>Array.from(suggestionDialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select')||[]);
    focusable()[0]?.focus();
    const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setSuggestion(null);}if(event.key==='Tab'){const targets=focusable();const first=targets[0],last=targets.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};
    document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('keydown',keyboard);previous?.focus();};
  },[suggestion]);
  if(loading)return <AppLayout><div className="flex items-center justify-center h-64"><Loader2 className="w-8 h-8 animate-spin text-blue-600"/></div></AppLayout>;
  if(!resume)return <AppLayout><div role="alert" className="card p-6"><h1 className="font-semibold text-xl">Could not open this resume</h1><p className="mt-2 text-red-600">{error||'Resume not found.'}</p><button onClick={()=>navigate('/dashboard')} className="btn-primary mt-5">Back to dashboard</button></div></AppLayout>;
  const enabled=parseEnabledSections(resume.enabledSections),order=parseSectionOrder(resume.sectionOrder),template=getTemplate(resume.templateId);
  const entries=(key:RelationKey)=>(currentResume.current?.[key]||[]) as unknown as EditableEntry[];
  const setEntries=(key:RelationKey,value:EditableEntry[])=>update({[key]:value} as Partial<Resume>);
  function editEntry(key:RelationKey,entryKey:string,updates:EditableEntry){setEntries(key,entries(key).map(entry=>entry._key===entryKey?{...entry,...updates}:entry));}
  function addEntry(section:Exclude<SectionId,'summary'>){const key=relationFor[section];if(entries(key).length>=100){toast.warning('Section limit','Each section can contain up to 100 entries.');return;}const empty:EditableEntry={...Object.fromEntries(ENTRY_FIELDS[key].map(field=>[field,''])),_key:crypto.randomUUID()};if(key==='skills')empty.category='technical';if(key==='experiences'||key==='volunteer')empty.isCurrent=false;update({[key]:[...entries(key),empty],enabledSections:{...parseEnabledSections(currentResume.current?.enabledSections),[section]:true}} as Partial<Resume>);}
  function moveEntry(key:RelationKey,from:number,to:number){const rows=[...entries(key)];if(to<0||to>=rows.length)return;rows.splice(to,0,rows.splice(from,1)[0]);setEntries(key,rows);}
  function moveSection(from:number,to:number){if(to<0||to>=order.length)return;const next=[...order];next.splice(to,0,next.splice(from,1)[0]);update({sectionOrder:next});}
  async function leave(){if(await save())navigate('/dashboard');else toast.error('Could not save','Your edits are preserved in this browser. Retry saving before leaving.');}
  async function exportDocument(format:'pdf'|'docx'|'txt'|'json'){
    if(!currentResume.current)return;setExporting(format);const snapshot=currentResume.current;const filename=(snapshot.fullName||snapshot.title||'resume').replace(/[^\p{L}\p{N}_-]+/gu,'_');
    try{
      await api.post('/resumes/'+id+'/export-check',{format});
      if(format==='pdf')downloadBlob(`${filename}.pdf`,await createResumePDF(snapshot));
      if(format==='txt')downloadText(`${filename}.txt`,resumeToText(snapshot));
      if(format==='json')downloadBlob(`${filename}.json`,new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));
      if(format==='docx')await exportTextDOCX({title:snapshot.fullName||snapshot.title,subtitle:[snapshot.professionalTitle,[snapshot.email,snapshot.phone,[snapshot.city,snapshot.country].filter(Boolean).join(', '),snapshot.linkedinUrl,snapshot.githubUrl,snapshot.portfolioUrl].filter(Boolean).join(' · ')].filter(Boolean).join('\n'),sections:resumeBlocks(snapshot).map(block=>({heading:block.heading,text:block.entries.map(entry=>[entry.title,entry.subtitle,entry.date,...entry.lines,...entry.links||[]].filter(Boolean).join('\n')).join('\n\n')})),filename:`${filename}.docx`,...{paperSize:snapshot.paperSize,fontFamily:snapshot.fontFamily,fontSize:snapshot.fontSize,pageMargin:snapshot.pageMargin,lineSpacing:snapshot.lineSpacing}});
      toast.success(`${format.toUpperCase()} downloaded`);
    }catch(err){toast.error('Export failed',err instanceof Error?err.message:'Could not create file');}finally{setExporting('');}
  }
  async function summaryAI(){
    const snapshot=currentResume.current;if(!snapshot)return;setAiBusy('summary');const identity=id;
    try{const result=await api.post<{summaries:string[]}>('/ai/summary',{name:snapshot.fullName,title:snapshot.professionalTitle||snapshot.targetRole,experience:resumeToText(snapshot),skills:snapshot.skills.map(s=>s.name).join(', '),tone});if(documentIdentity.current===identity)setSuggestion({kind:'summary',original:snapshot.summary||'',values:result.summaries});}catch(err){toast.error('AI request failed',err instanceof Error?err.message:'Try again');}finally{if(documentIdentity.current===identity)setAiBusy('');}
  }
  async function enhanceAI(entry:EditableEntry){
    if(!entry.description){toast.warning('Add a description','AI can improve your existing wording.');return;}const key=String(entry._key);setAiBusy(key);const identity=id;
    try{const result=await api.post<{enhanced:string;explanation:string}>('/ai/enhance',{original:entry.description,jobTitle:entry.jobTitle,company:entry.company,tone});if(documentIdentity.current===identity&&entries('experiences').some(e=>e._key===key))setSuggestion({kind:'experience',key,original:String(entry.description),values:[result.enhanced],explanation:result.explanation});}catch(err){toast.error('AI request failed',err instanceof Error?err.message:'Try again');}finally{if(documentIdentity.current===identity)setAiBusy('');}
  }
  function applySuggestion(value:string){
    if(!suggestion)return;if(suggestion.kind==='summary'){if((currentResume.current?.summary||'')!==suggestion.original){toast.warning('Your summary changed','Generate a new suggestion so your latest edits are included.');return;}update({summary:value});}
    else{const target=entries('experiences').find(e=>e._key===suggestion.key);if(!target){toast.warning('Entry removed','This suggestion belongs to a removed experience.');setSuggestion(null);return;}if(target.description!==suggestion.original){toast.warning('Your description changed','Generate a new suggestion so your latest edits are included.');return;}editEntry('experiences',suggestion.key!,{description:value});}setSuggestion(null);
  }
  async function analyze(action:'review'|'job-match'|'keywords'|'tailor'){
    if(!currentResume.current)return;if(action!=='review'&&!job.trim()){toast.warning('Add a job description');return;}setAiBusy(action);setAiResult(null);const identity=id;
    try{
      if(action==='tailor'){
        if(!await save())throw new Error('Save your latest changes before creating a tailored version.');
        const result=await api.post<{resume:Resume;changes:string[]}>('/ai/tailor',{resumeId:currentResume.current.id,jobDescription:job});if(documentIdentity.current!==identity)return;toast.success('Tailored copy created','Review all suggested claims before using this version.');navigate(`/resumes/${result.resume.id}/edit`);
      }else{const result=await api.post<Record<string,unknown>>(`/ai/${action}`,{resumeText:resumeToText(currentResume.current),...(action==='review'?{}:{jobDescription:job})});if(documentIdentity.current===identity)setAiResult(result);}
    }catch(err){toast.error('AI request failed',err instanceof Error?err.message:'Try again');}finally{if(documentIdentity.current===identity)setAiBusy('');}
  }
  function uploadPhoto(file:File){
    if(!['image/png','image/jpeg'].includes(file.type)||file.size>1024*1024){toast.error('Choose a PNG or JPEG smaller than 1 MB.');return;}
    const identity=id;const reader=new FileReader();reader.onload=()=>{if(documentIdentity.current===identity)update({photoUrl:String(reader.result)});};reader.onerror=()=>toast.error('Photo could not be read');reader.readAsDataURL(file);
  }
  function aiButton(label:string,onClick:()=>void,busyKey:string){return <button type="button" onClick={onClick} disabled={Boolean(aiBusy)||aiConfigured===false} className="btn-secondary btn-sm text-violet-700 dark:text-violet-300">{aiBusy===busyKey?<Loader2 className="w-4 h-4 animate-spin"/>:<Sparkles className="w-4 h-4"/>}{label}</button>;}
  const checklist=[['Name',Boolean(resume.fullName?.trim())],['Contact',Boolean(resume.email?.trim()||resume.phone?.trim())],['Professional title',Boolean(resume.professionalTitle?.trim())],['Summary',Boolean(resume.summary?.trim())],['Experience or projects',resume.experiences.some(e=>e.jobTitle.trim()&&e.company.trim())||resume.projects.some(e=>e.name.trim())],['Education',resume.educations.some(e=>e.institution.trim())],['Skills',resume.skills.some(e=>e.name.trim())]] as [string,boolean][];
  const completion=Math.round(checklist.filter(([,filled])=>filled).length/checklist.length*100);
  return <div className="min-h-screen flex flex-col bg-slate-100 dark:bg-slate-900">
    <header className="sticky top-0 z-30 bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700 px-3 sm:px-5 py-3 flex flex-wrap items-center gap-2">
      <button onClick={()=>void leave()} className="btn-ghost btn-sm" aria-label="Save and return to dashboard"><ChevronLeft className="w-4 h-4"/><span className="hidden sm:inline">Dashboard</span></button>
      <label className="sr-only" htmlFor="resume-title">Resume title</label><input id="resume-title" value={resume.title} maxLength={150} onChange={e=>update({title:e.target.value})} className="min-w-0 flex-1 max-w-xs bg-transparent text-sm font-semibold dark:text-white border-b border-transparent focus:border-blue-500 outline-none p-1"/>
      <span role="status" className={`text-xs ${saveStatus==='error'?'text-red-600':saveStatus==='saved'?'text-green-600':'text-amber-600'}`}>{saveStatus==='saved'?'Saved':saveStatus==='saving'?'Saving…':saveStatus==='error'?'Save failed':'Unsaved changes'}</span>
      <div className="flex items-center gap-1 sm:ml-auto"><button onClick={undo} disabled={!historyCount.undo} aria-label="Undo change" className="btn-ghost btn-sm"><Undo2 className="w-4 h-4"/></button><button onClick={redo} disabled={!historyCount.redo} aria-label="Redo change" className="btn-ghost btn-sm"><Redo2 className="w-4 h-4"/></button><button onClick={()=>void save()} disabled={saveStatus==='saving'} className="btn-secondary btn-sm"><Save className="w-4 h-4"/><span className="hidden sm:inline">Save</span></button>
        <details className="relative"><summary className="btn-primary btn-sm cursor-pointer list-none">{exporting?<Loader2 className="w-4 h-4 animate-spin"/>:<Download className="w-4 h-4"/>}Export</summary><div className="absolute right-0 mt-2 w-48 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 shadow-xl p-2 z-40">{(['pdf','docx','txt','json'] as const).map(format=><button key={format} onClick={()=>void exportDocument(format)} disabled={Boolean(exporting)} className="btn-ghost w-full justify-start text-sm">Download {format.toUpperCase()}</button>)}</div></details>
      </div>
    </header>
    {error&&<div role="alert" className="px-5 py-3 bg-red-50 text-red-700 text-sm">{error} Your edits remain in this browser. <button onClick={()=>void save()} className="underline font-semibold ml-2">Retry saving</button></div>}
    {recovery&&<div role="status" className="px-5 py-3 bg-amber-50 text-amber-900 flex flex-wrap items-center gap-3 text-sm"><span>There is an unsaved draft from your last session.</span><button onClick={restore} className="btn-secondary btn-sm">Restore draft</button><button onClick={discardRecovery} className="btn-ghost btn-sm">Use saved version</button></div>}
    <div className="lg:hidden flex bg-white dark:bg-slate-800 border-b"><button onClick={()=>setMobilePreview(false)} className={`flex-1 py-3 font-medium ${!mobilePreview?'text-blue-600':''}`}>Edit</button><button onClick={()=>setMobilePreview(true)} className={`flex-1 py-3 font-medium flex items-center justify-center gap-2 ${mobilePreview?'text-blue-600':''}`}><Eye className="w-4 h-4"/>Preview</button></div>
    <div className="flex flex-1 min-h-0">
      <aside className={`w-full lg:w-[460px] xl:w-[500px] flex-shrink-0 bg-white dark:bg-slate-800 border-r border-slate-200 dark:border-slate-700 ${mobilePreview?'hidden lg:block':''}`}>
        <nav aria-label="Editor panels" className="grid grid-cols-4 border-b border-slate-200 dark:border-slate-700 sticky top-[69px] bg-white dark:bg-slate-800 z-10">{(['content','design','sections','job'] as const).map(tab=><button key={tab} onClick={()=>setPanel(tab)} aria-current={panel===tab?'page':undefined} className={`py-3 text-sm capitalize font-medium ${panel===tab?'text-blue-600 border-b-2 border-blue-600':'text-slate-500'}`}>{tab==='job'?'ATS & job':tab}</button>)}</nav>
        <div className="p-4 space-y-4">
          {panel==='content'&&<>
            <div className="card p-4"><div className="flex justify-between text-sm font-medium mb-2"><span>Resume completeness</span><span>{completion}%</span></div><div className="h-2 rounded-full bg-slate-200 dark:bg-slate-700"><div className="bg-blue-600 h-2 rounded-full transition-all" style={{width:`${completion}%`}}/></div><p className="text-xs text-slate-500 mt-3">{checklist.filter(([,filled])=>!filled).map(([label])=>label).join(' · ')||'Core details are filled in. Review your wording before applying.'}</p></div>
            <details open className="border-b border-slate-200 dark:border-slate-700 pb-4"><summary className="cursor-pointer font-semibold py-3">Personal information</summary><div className="grid grid-cols-2 gap-3 mt-2">{personalFields.map(([field,label])=><label key={field} className="label">{label}<input className="input mt-1" type={field==='email'?'email':'text'} value={String(resume[field]||'')} maxLength={field.toLowerCase().includes('url')?2000:200} onChange={e=>update({[field]:e.target.value})}/></label>)}</div><label className="label mt-4">Optional photo<input className="input mt-1" type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)uploadPhoto(file);}}/></label>{resume.photoUrl&&<button onClick={()=>update({photoUrl:''})} className="btn-ghost btn-sm mt-2 text-red-600">Remove photo</button>}<p className="text-xs text-slate-500 mt-2">Photos are optional. A text-only resume is the safest choice for ATS uploads.</p></details>
            {order.map(section=><details key={section} open={section==='summary'||section==='experience'} className="border-b border-slate-200 dark:border-slate-700 pb-4"><summary className="cursor-pointer font-semibold py-3">{SECTION_LABELS[section]}{!enabled[section]&&<span className="ml-2 text-xs text-slate-400 font-normal">hidden in exports</span>}</summary>
              {section==='summary'?<div className="space-y-3 mt-2"><label className="sr-only" htmlFor="summary">Professional summary</label><textarea id="summary" className="textarea min-h-[140px]" value={resume.summary||''} maxLength={12000} onChange={e=>update({summary:e.target.value})} placeholder="Describe your background, verified achievements and value in 2–4 sentences."/><div className="flex gap-2 flex-wrap">{aiButton('Generate summary',()=>void summaryAI(),'summary')}<select aria-label="AI writing tone" className="input w-auto text-sm" value={tone} onChange={e=>setTone(e.target.value)}><option value="professional">Professional</option><option value="concise">Concise</option><option value="confident">Confident</option></select></div></div>:<div className="space-y-4 mt-2">{entries(relationFor[section]).map((entry,index)=>{
                const key=relationFor[section],entryKey=String(entry._key);return <div key={entryKey} className="bg-slate-50 dark:bg-slate-900/50 rounded-xl border border-slate-200 dark:border-slate-700 p-3 space-y-3" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const data=event.dataTransfer.getData('application/cv-entry');if(data){const parsed=JSON.parse(data) as {key:RelationKey;index:number};if(parsed.key===key)moveEntry(key,parsed.index,index);}}}>
                  <div className="flex items-center gap-1"><button draggable onDragStart={event=>event.dataTransfer.setData('application/cv-entry',JSON.stringify({key,index}))} aria-label={`Drag ${SECTION_LABELS[section]} entry ${index+1}`} className="btn-ghost btn-sm cursor-grab"><GripVertical className="w-4 h-4"/></button><span className="text-xs text-slate-500 flex-1">Entry {index+1}</span><button onClick={()=>moveEntry(key,index,index-1)} disabled={index===0} aria-label="Move entry up" className="btn-ghost btn-sm"><ArrowUp className="w-3 h-3"/></button><button onClick={()=>moveEntry(key,index,index+1)} disabled={index===entries(key).length-1} aria-label="Move entry down" className="btn-ghost btn-sm"><ArrowDown className="w-3 h-3"/></button><button onClick={()=>{if(entries(key).length<100)setEntries(key,[...entries(key).slice(0,index+1),{...entry,id:undefined,_key:crypto.randomUUID()},...entries(key).slice(index+1)]);}} aria-label="Duplicate entry" className="btn-ghost btn-sm"><Copy className="w-3 h-3"/></button><button onClick={()=>setEntries(key,entries(key).filter(e=>e._key!==entryKey))} aria-label="Remove entry" className="btn-ghost btn-sm text-red-500"><Trash2 className="w-3 h-3"/></button></div>
                  <div className="grid grid-cols-2 gap-3">{ENTRY_FIELDS[key].map(field=><label key={field} className={`label ${longFields.has(field)?'col-span-2':''}`}>{fieldLabels[field]}{longFields.has(field)?<textarea className="textarea mt-1 text-sm min-h-[90px]" value={String(entry[field]||'')} maxLength={field==='achievements'?10000:key==='experiences'?20000:12000} onChange={e=>editEntry(key,entryKey,{[field]:e.target.value})}/>:field==='category'?<select className="input mt-1 text-sm" value={String(entry[field]||'technical')} onChange={e=>editEntry(key,entryKey,{[field]:e.target.value})}>{['technical','soft','language','tool'].map(cat=><option key={cat} value={cat}>{cat}</option>)}</select>:<input className="input mt-1 text-sm" type={field==='email'?'email':'text'} value={String(entry[field]||'')} disabled={field==='endDate'&&Boolean(entry.isCurrent)} maxLength={field.toLowerCase().includes('url')?2000:field==='technologies'?2000:200} onChange={e=>editEntry(key,entryKey,{[field]:e.target.value})}/>}</label>)}</div>
                  {(key==='experiences'||key==='volunteer')&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(entry.isCurrent)} onChange={e=>editEntry(key,entryKey,{isCurrent:e.target.checked,...e.target.checked?{endDate:''}:{}})}/>Current role</label>}
                  {key==='experiences'&&aiButton('Improve description',()=>void enhanceAI(entry),entryKey)}
                </div>;
              })}<button onClick={()=>addEntry(section)} className="btn-secondary btn-sm w-full"><Plus className="w-4 h-4"/>Add {SECTION_LABELS[section]}</button></div>}
              </details>)}
          </>}
          {panel==='design'&&<>
            <label className="label">Template<select className="input mt-1" value={resume.templateId} onChange={e=>{const selected=getTemplate(e.target.value);update({templateId:selected.id,accentColor:selected.accentColor,fontFamily:selected.font});}}>{TEMPLATE_LIST.map(t=><option key={t.id} value={t.id} disabled={!['classic-professional','modern-minimalist','two-column'].includes(t.id)&&user?.plan!=='pro'&&user?.plan!=='premium'}>{t.name}{!['classic-professional','modern-minimalist','two-column'].includes(t.id)?' · Pro':''}</option>)}</select></label><p className="text-sm text-slate-500">{template.description}</p>
            {!template.atsFriendly&&<div className="text-sm text-amber-700 dark:text-amber-400 p-3 bg-amber-50 dark:bg-amber-950/20 rounded-lg">This layout uses columns. Choose a single-column template for the most predictable ATS reading order.</div>}
            <div className="grid grid-cols-2 gap-4"><label className="label">Accent color<input className="mt-1 w-full h-10 rounded-lg cursor-pointer" type="color" value={resume.accentColor} onChange={e=>update({accentColor:e.target.value})}/></label>{([['fontFamily','Font',[['Helvetica','Sans serif'],['Times-Roman','Serif'],['Courier','Monospace']]],['fontSize','Text size',[['small','Small'],['medium','Medium'],['large','Large']]],['pageMargin','Margins',[['narrow','Narrow'],['normal','Normal'],['wide','Wide']]],['lineSpacing','Line spacing',[['compact','Compact'],['normal','Normal'],['relaxed','Relaxed']]],['paperSize','Paper size',[['a4','A4'],['letter','US Letter']]]] as [keyof Resume,string,string[][]][]).map(([field,label,options])=><label key={field} className="label">{label}<select className="input mt-1" value={String(resume[field])} onChange={e=>update({[field]:e.target.value})}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>)}</div><p className="text-xs text-slate-500">The preview uses the same generated PDF as your download. DOCX uses a simple editable document layout.</p>
          </>}
          {panel==='sections'&&<><h2 className="font-semibold">Order and visibility</h2><p className="text-sm text-slate-500">Drag a section or use the arrow buttons. Hidden sections stay saved but do not appear in downloads or AI analysis.</p>{order.map((section,index)=><div key={section} className="flex items-center gap-2 card p-3" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const from=Number(event.dataTransfer.getData('application/cv-section'));if(Number.isInteger(from)&&from>=0&&from<SECTION_IDS.length)moveSection(from,index);}}><button draggable onDragStart={event=>event.dataTransfer.setData('application/cv-section',String(index))} className="btn-ghost btn-sm cursor-grab" aria-label={`Drag ${SECTION_LABELS[section]}`}><GripVertical className="w-4 h-4"/></button><label className="flex-1 flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled[section]} onChange={e=>update({enabledSections:{...enabled,[section]:e.target.checked}})}/>{SECTION_LABELS[section]}</label><button onClick={()=>moveSection(index,index-1)} disabled={index===0} aria-label={`Move ${SECTION_LABELS[section]} up`} className="btn-ghost btn-sm"><ArrowUp className="w-4 h-4"/></button><button onClick={()=>moveSection(index,index+1)} disabled={index===order.length-1} aria-label={`Move ${SECTION_LABELS[section]} down`} className="btn-ghost btn-sm"><ArrowDown className="w-4 h-4"/></button></div>)}</>}
          {panel==='job'&&<><h2 className="font-semibold">Review and tailor</h2><p className="text-sm text-slate-500">Scores are AI estimates, not results from an employer's ATS. Add keywords only when they describe your real experience.</p><label className="label">Job description<textarea className="textarea min-h-[180px] mt-1" value={job} maxLength={30000} onChange={e=>setJob(e.target.value)} placeholder="Paste the job description here."/></label><div className="flex gap-2 flex-wrap">{aiButton('Resume review',()=>void analyze('review'),'review')}{aiButton('Job match',()=>void analyze('job-match'),'job-match')}{aiButton('Keyword gaps',()=>void analyze('keywords'),'keywords')}{aiButton('Create tailored copy',()=>void analyze('tailor'),'tailor')}</div>{aiResult&&<div className="space-y-4 card p-4">{Object.entries(aiResult).map(([key,value])=><div key={key}><h3 className="font-semibold text-sm capitalize mb-2">{key.replace(/([A-Z])/g,' $1')}</h3>{typeof value==='number'?<p className="font-bold text-xl text-blue-600">{value}% <span className="text-xs font-normal text-slate-500">estimated</span></p>:Array.isArray(value)?<ul className="space-y-2 text-sm">{value.map((item,index)=><li key={index} className="p-2 bg-slate-50 dark:bg-slate-900 rounded-lg">{typeof item==='string'?item:item&&typeof item==='object'?Object.values(item).filter(v=>typeof v==='string').join(' — '):String(item)}</li>)}</ul>:typeof value==='string'?<p className="text-sm">{value}</p>:null}</div>)}</div>}</>}
          {aiConfigured===false&&<p role="status" className="text-xs text-amber-700 dark:text-amber-400">AI is not configured on this server. Editing and exports are available.</p>}
        </div>
      </aside>
      <main className={`flex-1 min-w-0 p-4 sm:p-6 ${!mobilePreview?'hidden lg:block':''}`}>
        <div className="sticky top-[85px]"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="text-sm font-semibold text-slate-700 dark:text-slate-200">PDF preview · {resume.paperSize==='letter'?'US Letter':'A4'}</h2><p className="text-xs text-slate-500 mt-1">{previewBusy?'Updating preview…':'Selectable text · automatic page breaks'}</p></div>{previewURL&&<a href={previewURL} target="_blank" rel="noreferrer" className="btn-secondary btn-sm"><Eye className="w-4 h-4"/>Open preview</a>}</div>
          {previewError&&<p role="alert" className="text-sm text-red-700 bg-red-50 rounded-lg p-3 mb-3">Preview could not update: {previewError}{previewURL?' The previous preview is still shown.':''}</p>}
          {previewURL?<iframe title="Generated resume PDF preview" src={`${previewURL}#toolbar=1&navpanes=0&zoom=page-width`} className="w-full bg-white rounded-xl shadow-xl border border-slate-300" style={{height:'calc(100vh - 160px)',minHeight:420}}/>:<div className="min-h-[480px] flex items-center justify-center bg-white dark:bg-slate-800 rounded-xl">{previewBusy?<Loader2 className="w-8 h-8 animate-spin text-blue-600"/>:<span className="text-slate-500">PDF preview will appear here.</span>}</div>}
          <p className="lg:hidden text-xs text-slate-500 mt-3">If your browser does not display embedded PDFs, use Open preview.</p>
        </div>
      </main>
    </div>
    {suggestion&&<div role="dialog" aria-modal="true" aria-labelledby="ai-suggestion-title" className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4" onClick={()=>setSuggestion(null)}><div ref={suggestionDialog} className="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl p-6 max-w-2xl w-full max-h-[85vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-2 mb-4"><Sparkles className="w-5 h-5 text-violet-600"/><h2 id="ai-suggestion-title" className="font-bold text-lg flex-1">Review AI suggestions</h2><button onClick={()=>setSuggestion(null)} aria-label="Close AI suggestions" className="btn-ghost btn-sm"><X className="w-4 h-4"/></button></div><p className="text-sm text-slate-500 mb-4">Keep only wording that matches your actual work. Applying a suggestion can be undone.</p>{suggestion.explanation&&<p className="text-sm text-violet-600 mb-4">{suggestion.explanation}</p>}{suggestion.values.map((value,index)=><div key={index} className="border border-slate-200 dark:border-slate-700 p-4 rounded-xl mb-3"><p className="whitespace-pre-wrap text-sm leading-relaxed">{value}</p><button onClick={()=>applySuggestion(value)} className="btn-primary btn-sm mt-3"><Check className="w-4 h-4"/>Use this wording</button></div>)}</div></div>}
  </div>;
}

