import PublicLayout from '../components/PublicLayout';
export default function TermsPage() {
  return <PublicLayout title="Terms of use" description="These terms explain the current service behavior and the responsibilities involved in creating application documents."><article className="card p-6 sm:p-10 max-w-4xl space-y-7 leading-relaxed text-sm">
    <section><h2 className="text-lg font-semibold mb-2">Using the service</h2><p>CV Creator Pro helps you create, save, tailor, and export resumes and cover letters. Keep your account credentials private and use the service only for content you have the right to provide. Do not attempt to access another user's documents, bypass usage limits, or interfere with the service.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Your documents</h2><p>You retain control of the resume and cover-letter content you provide. The service processes it to deliver editing, storage, exports, and the AI actions you request. You can download your documents and delete saved content or your account.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">AI drafts and application accuracy</h2><p>AI suggestions can contain errors, omissions, or wording that does not reflect your experience. Review every generated draft before applying. Do not add qualifications, employers, dates, or achievements you cannot support. Match and review scores are estimates for guidance and are not scores from an employer's ATS. The service does not guarantee interview invitations, job offers, or compatibility with every recruitment system.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Availability and limits</h2><p>Account limits are displayed on the Plans page and in Settings. AI requests require a configured provider and available allowance. Service availability depends on the hosting, database, and external providers. Save and export important documents for your own records.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Payments</h2><p>Paid subscriptions are not enabled in the current application. No checkout or payment is collected. A deployment operator must provide clear prices, renewal, cancellation, and refund terms before activating a payment integration.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Operator and applicable terms</h2><p>Before public launch, the deployment operator must add their legal identity, support contact, applicable jurisdiction, and any service-specific contractual terms. These product terms describe the implemented application and do not replace those operator disclosures.</p></section>
  </article></PublicLayout>;
}
