import PublicLayout from '../components/PublicLayout';
import { SITE, supportMailto } from '../lib/site';

export default function TermsPage() {
  return <PublicLayout title="Terms of service" description={`Last updated ${SITE.lastUpdated}`}><article className="card p-6 sm:p-10 max-w-4xl space-y-7 leading-relaxed text-sm">
    <section><h2 className="text-lg font-semibold mb-2">Service and operator</h2><p>{SITE.name} is a self-service resume creation application operated by {SITE.operator} in {SITE.location}. The service helps users create, edit, analyse, and export their own resumes and cover letters. It is not a recruitment agency, job board, employer, or application-submission service. By creating an account or using the service, you agree to these terms.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Eligibility and accounts</h2><p>You must be legally able to enter a contract in your country. Provide accurate account information, protect your password, and notify us if you suspect unauthorized access. You are responsible for activity on your account.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Acceptable use</h2><p>Use the service only for lawful content you have the right to process. You may not impersonate another person, fabricate credentials, upload malicious content, attempt to access another user's documents, scrape the service, bypass plan limits, resell access, or interfere with security or availability. We may restrict accounts that violate these terms.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Your content and AI suggestions</h2><p>You retain ownership of the content you provide. You grant us the limited permission needed to store, process, and export it at your request. Optional AI features send relevant content to the providers described in our Privacy Policy. Optional AI features send relevant content to the providers described in our Privacy Policy. Automated suggestions may contain errors and must be reviewed. Do not claim qualifications, experience, dates, or achievements you cannot support. Scores and compatibility guidance are estimates; we do not guarantee ATS results, interviews, or employment.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Plans, billing, and cancellation</h2><p>Current features, usage limits, prices, and billing intervals are shown on the Plans page. Prices are in US dollars. Monthly plans are charged monthly and annual plans are charged as one payment for the year. Any applicable taxes and the total due are shown at checkout. When paid subscriptions are available, purchases are processed by Lemon Squeezy as merchant of record, subject to the terms presented at checkout. Paid access begins after payment is confirmed. Subscriptions renew automatically until cancelled. Use the customer billing portal linked from the Plans page to cancel before the next renewal. Cancellation stops future charges and access continues through the paid period unless an applicable rule ends it earlier. A free account does not require payment details.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Refunds</h2><p>We offer a full refund of your initial subscription payment when you request it within 14 days. The process and renewal rules are described in the <a className="text-blue-600 hover:underline" href="/refunds">Refund Policy</a>. Mandatory consumer rights continue to apply.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Availability and liability</h2><p>We work to keep the service available and protect saved data, but uninterrupted operation cannot be guaranteed. Keep copies of important documents. To the maximum extent permitted by law, liability is limited to the amount you paid for the service during the twelve months before the event giving rise to the claim. The liability limit does not apply to fraud, wilful misconduct, or liability that cannot legally be limited.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Changes, termination, and law</h2><p>We may update the service or these terms for legal, security, or product reasons and publish the revised date. Any changed subscription price must be communicated before it takes effect. You may stop using the service at any time. Cancel a renewing subscription before deleting your account in Settings. These terms are governed by the laws of Morocco, subject to any mandatory consumer protections and dispute rights that apply in your country. Contact us first so we can try to resolve a dispute.</p></section>
    <section><h2 className="text-lg font-semibold mb-2">Contact</h2><p>Questions about these terms can be sent to <a className="text-blue-600 hover:underline" href={supportMailto}>{SITE.supportEmail}</a>.</p></section>
  </article></PublicLayout>;
}
